Validate locators searching by their height
AleoHQ/snarkOS pull request #1538
Opened 2022-01-10 11:19 UTC by ljedrz

`get_block_height` is super slow compared to `get_block_hash`; using the latter to validate the block locators reduces the duration of the associated loop from hundreds of ms to **zero** ms.

2022-01-10 11:26 UTC, niklaslong approved these changes
Seems fine to me 👍

2022-01-10 14:04 UTC, HarukaMa requested changes
If the ledger has forked, the incoming block hash for the forked block won't match the one on the ledger and it'll be reported as an error, effectively stopping the node from recovering from the fork situation.

2022-01-10 14:06 UTC, ljedrz commented
It's weird that the tests haven't caught this; I'll see if I can salvage some of this perf improvement.

2022-01-12 18:57 UTC, ljedrz commented
Superseded by https://github.com/AleoHQ/snarkOS/pull/1548.

2022-01-12 18:57 UTC, closed without merging