optimize load_blocks
AleoHQ/snarkOS pull request #2160
Opened 2022-12-06 06:58 UTC by ghostant-1017

## Motivation

Some code optimizations

2022-12-08 21:48 UTC, howardwu commented on node/messages/src/helpers/block_locators.rs
> +            let last_recent_hash = recents.get(&last_recent_height).expect("Unreachable");
Let's revert this one since logically it should be optimized the same under the hood and mitigates a (unlikely) panic.

2022-12-08 21:49 UTC, howardwu commented on node/cdn/src/blocks.rs
> +    // And end_height must be less or equal than cdn_height, so we choose min(end_height, cdn_height)
```suggestion
    // If the end height is not specified, set it to the CDN height.
    // If the end height is greater than the CDN height, set the end height to the CDN height.
```

2022-12-08 21:50 UTC, howardwu commented on node/src/helpers.rs
> +    let mut checkpoints = IndexMap::with_capacity((latest_height / CHECKPOINT_INTERVAL).try_into()?);
Great catch! Thank you :)

2022-12-08 21:50 UTC, howardwu requested changes
LGTM pending changes, thanks!

2023-02-10 02:54 UTC, ghostant-1017 commented
CI is timeout

2023-06-16 03:34 UTC, howardwu approved these changes
LGTM

2023-06-16 03:34 UTC, merged