test: worker tests
AleoHQ/snarkOS pull request #2559
Opened 2023-07-19 19:20 UTC by joske

Split out some of the `Gateway` API into a trait so that we can mock it.

Add tests for `Worker`

2023-07-20 13:51 UTC, ljedrz commented on node/narwhal/src/gateway.rs
> +pub trait ReliableTransport<N: Network>: Send + Sync {
this trait could use a description; why makes it reliable? should the methods perform retransmission on failure? should there be some ACK mechanism? if reliability is a factor, why are the methods infallible?

2023-07-20 13:52 UTC, ljedrz requested changes
Since it's more than just tests, I'm missing a description, and the creation of a new trait and the related refactoring should be in its own commit.

The use of a trait object in the `Worker` could either be a part of that or - preferably - a separate commit as well.

2023-07-20 13:56 UTC, ljedrz commented on node/narwhal/src/worker.rs
> +        LedgerService<N: Network> {}
I'd prefer this to be called either `Ledger` or `LedgerProvider`, so as not to have `impl LedgerService for LedgerService`

2023-07-20 13:57 UTC, ljedrz commented on node/narwhal/src/worker.rs
> +    async fn test_process_solution_ok() {
applies to this one and the rest of the tests - they need some newlines that at least separate the setup part from the actual test bits

2023-07-20 14:06 UTC, joske commented on node/narwhal/src/gateway.rs
> +pub trait ReliableTransport<N: Network>: Send + Sync {
Naming is hard. I'm open to another name. It's just to facilitate testing/mocking.

2023-07-20 14:38 UTC, ljedrz approved these changes
LGTM :ok_hand:

2023-07-21 05:00 UTC, howardwu approved these changes
LGTM

2023-07-21 14:30 UTC, merged