feat(cli): add sign and verify sub commands to the account command
AleoHQ/snarkOS pull request #2909
Opened 2023-12-09 20:45 UTC by Meshiest

## Motivation

Signatures can be created/verified programmatically both from [AleoHQ/sdk](https://github.com/AleoHQ/sdk) (web-ui via [aleo.tools](https://aleo.tools/account)) and within [leo](https://developer.aleo.org/leo/language/#signatures) but not from the official snarkOS CLI.

This PR creates two straightforward commands for working with Aleo signatures:

- `snarkos account sign -k <privateKey> -m <message> -s [seed]`
    outputs an Aleo signature of the message, signed with the private key.
- `snarkos account verify -s <signature> -m <message> -a <account>`
    outputs `verified` or `invalid` if the signature is verified or invalid respectfully.

## Test Plan

No code outside of the new features were changed and test coverage is as follows:

- Signature creation (unseeded)
- Seeded signature creation
- Valid signature verification
- Invalid signature verification (message is incorrect)
- Invalid signature verification (address is incorrect)

## Related PRs

No related work

2023-12-21 18:33 UTC, howardwu commented
@d0cd do we want to support this signature call? It does not match with the signature scheme used in Leo and Aleo instructions. If we're fine with non-compatibility, then we can merge this in.

2023-12-22 00:29 UTC, Meshiest commented
@howardwu I've added support signing for any aleo literal value, with regular plaintext as bytes fallback.

![image](https://github.com/AleoHQ/snarkOS/assets/4142480/6ffa80e7-fe0f-4c68-9f77-486d9b6650f2)
![image](https://github.com/AleoHQ/snarkOS/assets/4142480/508bd311-3c1d-42e1-98fe-643152d700f0)
```leo
program helloworld_nefsp0h.aleo {
  transition main(public s: signature, a: address, m: field) -> bool {
      return s.verify(a, m);
  }
}
```

`leo run main sign1w0gwak002kqxyqxknkft7zxj45vvthk3nd3jqy29xlj2qtllvuqdqjhn5y3jvj56pw44vqppxynkv3wywh7kk02vauvcgymrhdk5sqawfz3e8r7u2tm5h7jun68vsmc9 aleo18pfumcshatzm2r6te5erxeaxkrynsk2qkdpfy3wd90fhq573cgysj9kpx4 5field`

2023-12-23 19:07 UTC, HarukaMa commented
I don't think this kind of ambiguity of input message format is good though - what if we want to sign a string which happens to be able to interpreted as `Literal`? Plus in the future we might have string type as well.

This is mainly because we probably will want to have the capability to sign arbitrary content.

2023-12-23 22:18 UTC, Meshiest commented
@HarukaMa makes a very good point. I've added a flag `-l`/ `--literal` gate the literal parsing to ensure the `sign` and `verify` commands have compatibility with the wasm sdk (which does not have compatibility with signing aleo literals) by default, and compatibility with leo when present.

![image](https://github.com/AleoHQ/snarkOS/assets/4142480/68fbc254-b7d9-460d-a6df-e6cf0c672c50)
![image](https://github.com/AleoHQ/snarkOS/assets/4142480/2f2566f8-08c5-4ee8-8123-ffbc40081b97)

2023-12-25 00:12 UTC, d0cd commented
@Meshiest thank you for your contribution! 
I think the default option should be to support signing snarkVM datatypes (`Value`).
We can then add a `--raw, -r` flag to support signing raw messages.

2023-12-25 00:48 UTC, Meshiest commented
@d0cd I've inverted `--literal` into `--raw` as requested

2023-12-25 01:08 UTC, Meshiest commented
I can reword the language in the CLI and README to be "snarkVM values" if desired

2024-01-12 01:34 UTC, Meshiest commented
zeroize doesn't support PathBuf so I had to move that parsing from `clap` derive macro into the enum handler

2024-01-18 21:35 UTC, d0cd requested changes
@Meshiest awesome work on this PR! 
Left some suggestions and some nits.
I would also double check that the signature produced by the CLI tool actually works with the `sign.verify` instruction

2024-01-18 21:35 UTC, d0cd commented on README.md
> +Note, using the `--raw` flag with the command will sign plaintext messages as bytes rather than [leo](https://leo-lang.org/) values such as `1u8` or `100field`.
```suggestion
Note, using the `--raw` flag with the command will sign plaintext messages as bytes rather than [Aleo](https://developer.aleo.org/aleo/language#data-types-and-values) values such as `1u8` or `100field`.
```

2024-01-18 21:35 UTC, d0cd commented on cli/src/commands/account.rs
> +        /// When enabled, parses the message as bytes instead of aleo literals
```suggestion
        /// When enabled, parses the message as bytes instead of Aleo literals
```

2024-01-18 21:35 UTC, d0cd commented on cli/src/commands/account.rs
> +        /// When enabled, parses the message as bytes instead of aleo literals
```suggestion
        /// When enabled, parses the message as bytes instead of Aleo literals
```

2024-01-18 21:35 UTC, d0cd commented on cli/src/commands/account.rs
> +/// Parse a raw leo input into fields
```suggestion
/// Parse a raw Aleo input into fields
```

2024-01-18 21:35 UTC, d0cd commented on cli/src/commands/account.rs
> +                aleo_literal_to_fields(&message).map_err(|_| anyhow!("Failed to parse a valid aleo literal"))?;
```suggestion
                aleo_literal_to_fields(&message).map_err(|_| anyhow!("Failed to parse a valid Aleo literal"))?;
```

2024-01-18 21:35 UTC, d0cd commented on cli/src/commands/account.rs
> +                aleo_literal_to_fields(&message).map_err(|_| anyhow!("Failed to parse a valid aleo literal"))?;
```suggestion
                aleo_literal_to_fields(&message).map_err(|_| anyhow!("Failed to parse a valid Aleo literal"))?;
```

2024-01-18 21:35 UTC, d0cd commented on cli/src/commands/account.rs
> +        Ok(if verified { "verified" } else { "invalid" }.to_string())
```suggestion
        match verified {
            true => Ok("✅ The signature is valid"),
            false =>  bail!("❌ The signature is invalid"),
        }
```

2024-01-18 21:35 UTC, d0cd commented on cli/src/commands/account.rs
> +    Ok(value.to_fields().into_iter().map(|f| f.eject_value()).collect())
```suggestion
    let value = snarkvm::console::Value::<Network>::from_str(input)?;
    Ok(value.to_field().collect())
```

2024-01-18 21:35 UTC, d0cd commented on cli/src/commands/account.rs
> +    Ok(value.to_fields().into_iter().map(|f| f.eject_value()).collect())
^ The idea is to use the console values directly.

2024-01-18 21:35 UTC, d0cd commented on cli/src/commands/account.rs
> +type A = snarkvm::circuit::AleoV0;
I believe this is not needed if you are using the console values.

2024-01-18 22:41 UTC, Meshiest commented
I've implemented all of your feedback (in one commit rather than a bunch of individual ones).

I've verified that the latest changes w/o the --raw flag work with the leo CLI (https://play.leo-lang.org/ is down)

![image](https://github.com/AleoHQ/snarkOS/assets/4142480/78eb152d-8020-4cd9-843b-6b8c902c7b5d)
![image](https://github.com/AleoHQ/snarkOS/assets/4142480/4d9276db-a632-4f7d-ad80-f0e241c54265)

```rs
program foo.aleo {
    transition main(public s: signature, a: address, m: field) -> bool {
      return s.verify(a, m);
    }
}
```

2024-01-19 15:29 UTC, Meshiest commented
As Leo Playground is back, here's a screenshot of it working there too 

![image](https://github.com/AleoHQ/snarkOS/assets/4142480/c3f21116-af46-4fa4-8edb-ed25c28ac1af)

2024-01-19 16:03 UTC, d0cd approved these changes
LGTM!

2024-03-13 00:10 UTC, howardwu commented
Apologies for the delay, just seeing this LGTM, proceeding to merge.

2024-03-13 00:10 UTC, merged