Bond balances in genesis
AleoHQ/snarkOS pull request #3016
Opened 2024-01-18 05:09 UTC by vicsn

## Motivation

We want to be able to bond balances in the genesis block

## Related PRs

https://github.com/AleoHQ/snarkVM/pull/2308

2024-01-18 17:16 UTC, d0cd commented
Should this target the `mainnet` branch?

2024-01-18 17:20 UTC, d0cd requested changes, later dismissed

2024-01-18 17:20 UTC, d0cd commented on node/router/src/lib.rs
Are these changes relevant?

2024-01-18 17:20 UTC, d0cd commented on node/bft/tests/common/primary.rs
> +    bonded_balances: IndexMap<Address<CurrentNetwork>, u64>,
```suggestion
    bonded_balances: IndexMap<Address<CurrentNetwork>, (Address<CurrentNetwork>, u64)>,
```

2024-01-18 17:20 UTC, d0cd commented on node/bft/tests/common/primary.rs
> +    bonded_balances: IndexMap<Address<CurrentNetwork>, u64>,
Ditto for the rest of type signatures

2024-02-13 02:20 UTC, raychu86 commented
Closing in favor of https://github.com/AleoHQ/snarkOS/pull/3091

2024-02-13 02:20 UTC, closed without merging