Clean up verbosity 0 logging messages and display one-line block sync
AleoHQ/snarkOS pull request #3328
Opened 2024-06-24 01:46 UTC by damons

## Motivation

Currently verbosity settings of the client are mixed with info, debug, and trace log levels.   When a user starts the node, the mix of messages is confusing and it's not clear if a node is connecting, syncing blocks, and working properly.  It's important to give immediate feedback to users that their node is syncing as quickly as possible without distractions.  This patch does two important things:

1.  When running with `--verbosity 0` it only displays `info` messages that give meaningful information to the user about:  peer connections (initial, drops, and refreshes) and block sync progress.
2. It removes the extra `\n\n`'s from the block advance and instead only prints: [{BLOCK_NUM}] {BLOCK_HASH} which gives a clear message to the user every time a block is added to the ledger.  When run with verbosity 0, the primary information a user sees is blocks being added to the ledger.  This gives immediate and clear feedback to the user that their client node is syncing properly and it shows the performance of the node.

Here's an example of `--verbosity 0` output using this PR:

<img width="906" alt="Screenshot 2024-06-23 at 8 29 11 PM" src="https://github.com/AleoNet/snarkOS/assets/4625104/8d084a81-2c01-4a22-9411-42499bb3d6b3">

Several files where changed from `info!` to `debug!` and vice versa.  Some `debug!`s were changed to `trace!` as some of the modules override the usual log levels which causes trace and debug logs to be produced at verbosity 0.  

## Test Plan

Compiled and run using `--verbosity 0` and the client output matches the above screenshot.

2024-06-24 08:52 UTC, joske approved these changes
LGTM, I'm all for cleaner, less noisy but still informative logs.

2024-07-02 21:53 UTC, raychu86 requested changes

2024-07-02 21:53 UTC, raychu86 commented on node/bft/ledger-service/src/ledger.rs
> +        tracing::info!("[{}] {}", block.height(), block.hash());
While more verbose, the previous message of `Advanced to lock {} at round {}` has been very valuable for debugging and parsing logs.

2024-07-02 21:53 UTC, raychu86 commented on node/bft/src/gateway.rs
> +        trace!("Starting the gateway for the memory pool...");
```suggestion
        info!("Starting the gateway for the memory pool...");
```

This should be an `info` log like all the other module bootup messages.

2024-07-02 21:53 UTC, raychu86 commented on node/bft/src/gateway.rs
> +            trace!("{CONTEXT} Disconnecting from '{peer_ip}' (unable to send)");
```suggestion
            warn!("{CONTEXT} Disconnecting from '{peer_ip}' - Failed to send '{name}': {e}");
```

We can unify the 2 log messages to a single one that matches the other disconnect warn messages.

2025-03-26 21:53 UTC, closed without merging