Remove --seed flag from account sign command
AleoHQ/snarkOS pull request #3382
Opened 2024-08-14 22:29 UTC by Meshiest

## Motivation

The `--seed` flag in the `leo account sign` command is insecure as `nonce`s in signatures are not intended to be seeded, reused, or shared. This PR removes that functionality to prevent anyone from accidentally using insecure functionality.

## Related PRs

- Same fix for leo cli: https://github.com/ProvableHQ/leo/pull/28323

2024-08-23 18:46 UTC, raychu86 approved these changes

2024-09-04 03:26 UTC, damons commented
This really should be merged for mainnet.

2024-09-10 01:02 UTC, aleojohn submitted a review, later dismissed
LGTM pending CI

2024-09-10 01:22 UTC, raychu86 requested changes
@Meshiest To resolve `cargo clippy`, you'll need to delete the line -  `utilities::ToBytes,` in `cli/src/commands/account.rs` on line 23, and then rerun `cargo +nightly clippy`.

2024-09-10 03:52 UTC, raychu86 commented
@Meshiest Looks like clippy is still failing - https://app.circleci.com/pipelines/github/AleoNet/snarkOS/331/workflows/f77b15c2-96fc-4809-870b-8c8cfd34a98e/jobs/4208. You'll need to rerun `cargo +nightly clippy` or manually fix that issue

2024-09-10 14:34 UTC, snarkworld approved these changes
Approved, pending CI

2024-09-10 15:27 UTC, raychu86 approved these changes

2024-09-10 19:50 UTC, merged