DPC tweaks
AleoHQ/snarkOS pull request #508
Opened 2020-10-26 16:39 UTC by ljedrz

Builds on https://github.com/AleoHQ/snarkOS/pull/498, the last 17 commits are new.

This PR targets allocations in the `snarkos-dpc` crate; this is achieved with, among others:
- removing redundant (re)allocations
- reordering code where possible
- using `std::borrow::Cow`
- reducing the scope of allocations (allocating later, using `drop` on collections in some long functions)
- reusing already-allocated vectors
- utilizing iterators more often
- passing arguments by value where the function requires ownership (in order to be able to consume some objects instead of cloning all references)

Posting as a draft, as there's still some possible tweaks left and I see potential for introducing some benchmarks.

2020-11-13 10:06 UTC, ljedrz commented
Rebased.

2020-11-20 01:36 UTC, howardwu commented on dpc/src/base_dpc/outer_circuit/outer_circuit_gadget.rs
> -    let mut serial_numbers_fe = Vec::with_capacity(old_serial_numbers.len());
Can we revert these changes?

Changing this gadget will invalidate the current outer-circuit-pk and -vk parameters used by testnet1.

I will confirm this has been caught by CI

2020-11-20 01:37 UTC, howardwu requested changes
Pending outer circuit gadget logical changes, this PR is ready for approval

2020-11-20 01:39 UTC, howardwu commented on dpc/src/base_dpc/outer_circuit/outer_circuit_gadget.rs
> -    let mut serial_numbers_fe = Vec::with_capacity(old_serial_numbers.len());
As we skip DPC tests in CI, this compatibility break isn't being checked. Running locally now

2020-11-20 01:59 UTC, howardwu approved these changes
Ran locally to confirm gadget changes did not affect parameters. LGTM!

2020-11-20 01:59 UTC, merged