Configure Dependabot to open PRs on staging branch
AleoHQ/snarkOS pull request #904
Opened 2021-07-04 22:06 UTC by howardwu

## Motivation

Configure Dependabot to open PRs on staging branch

2021-07-04 23:29 UTC, howardwu commented
@ljedrz @niklaslong it appears there's an unrelated failure affecting this PR's CI

2021-07-04 23:30 UTC, weikengchen approved these changes

2021-07-05 08:06 UTC, ljedrz commented on .github/dependabot.yml
> +  target_branch: "staging"
```suggestion
  target-branch: "staging"
```

`dependabot`'s docs suggest that this should be `target-branch` instead: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#target-branch

2021-07-05 08:08 UTC, ljedrz requested changes
I think we need to change the key from an underscore to a dash, as I commented on the diff; other than that it's a desirable change :+1:.

2021-07-05 09:52 UTC, niklaslong commented
Re-running the CI jobs fixes both failures in `snarkos-testing` and `rust-stable`.

2021-07-10 09:32 UTC, ljedrz approved these changes

2021-07-12 08:36 UTC, niklaslong approved these changes

2021-07-13 10:25 UTC, merged